2023-12-28 ｜ 01:18:33
Exception in thread Thread-1 (load_plugins):
2023-12-28 ｜ 01:18:34 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/loader.py", line 43, in load_plugins
    module = importlib.import_module(f'plugins.{plugin_folder}')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 75, in <module>
    with open(ban_dicts_path, 'w', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/filter/ban_dicts.json'
2023-12-28 ｜ 01:19:34 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 01:19:34 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 01:19:35
2023-12-28 ｜ 01:19:46 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 01:19:46 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 01:19:46
2023-12-28 ｜ 01:20:35 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 01:20:35 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 01:29:14
2023-12-28 ｜ 01:29:57 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 01:29:57 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 01:29:57
2023-12-28 ｜ 01:30:18 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 01:30:18 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 01:30:19
2023-12-28 ｜ 01:30:58 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 01:30:58 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:12:12
Exception in thread Thread-3 (websocket_):
2023-12-28 ｜ 14:12:12 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/websocket_client/__init__.py", line 84, in websocket_
    connections = config["connections"]
                  ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'connections'
Exception in thread Thread-1 (load_plugins):
2023-12-28 ｜ 14:12:12 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/loader.py", line 39, in load_plugins
    module = importlib.import_module(f'plugins.{plugin_folder}')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins.test_plugin'
2023-12-28 ｜ 14:13:28 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:13:28 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:13:45
Exception in thread Thread-3 (websocket_):
2023-12-28 ｜ 14:13:45 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/websocket_client/__init__.py", line 84, in websocket_
    connections = config["connections"]
                  ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'connections'
2023-12-28 ｜ 14:14:15 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:14:15 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:14:16
Exception in thread Thread-7 (_soyo1):
2023-12-28 ｜ 14:14:21 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-9 (_soyo1):
2023-12-28 ｜ 14:14:22 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-11 (_soyo1):
2023-12-28 ｜ 14:14:25 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
2023-12-28 ｜ 14:14:31 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:14:31 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:14:32
Exception in thread Thread-7 (_soyo1):
2023-12-28 ｜ 14:14:34 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-11 (_soyo1):
2023-12-28 ｜ 14:14:41 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-13 (_soyo1):
2023-12-28 ｜ 14:14:45 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-15 (_soyo1):
2023-12-28 ｜ 14:14:49 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
2023-12-28 ｜ 14:14:49 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:14:49 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:14:50
Exception in thread Thread-7 (_soyo1):
2023-12-28 ｜ 14:14:53 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
2023-12-28 ｜ 14:14:55 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:14:55 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:14:55
Exception in thread Thread-7 (_soyo1):
2023-12-28 ｜ 14:14:57 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-9 (_soyo1):
2023-12-28 ｜ 14:14:59 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-11 (_soyo1):
2023-12-28 ｜ 14:15:02 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-13 (_soyo1):
2023-12-28 ｜ 14:15:06 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-15 (_soyo1):
2023-12-28 ｜ 14:15:11 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-19 (_soyo1):
2023-12-28 ｜ 14:15:12 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
Exception in thread Thread-23 (_soyo1):
2023-12-28 ｜ 14:15:13 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['bot']['prefix']:
                  ~~~~~~^^^^^^^
KeyError: 'bot'
2023-12-28 ｜ 14:15:14 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:15:14 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:15:14
Exception in thread Thread-9 (_soyo1):
2023-12-28 ｜ 14:15:16 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-11 (_soyo1):
2023-12-28 ｜ 14:15:28 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-13 (_soyo1):
2023-12-28 ｜ 14:15:31 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-15 (_soyo1):
2023-12-28 ｜ 14:15:37 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-17 (_soyo1):
2023-12-28 ｜ 14:15:41 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-19 (_soyo1):
2023-12-28 ｜ 14:15:42 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-21 (_soyo1):
2023-12-28 ｜ 14:15:42 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-23 (_soyo1):
2023-12-28 ｜ 14:15:46 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-25 (_soyo1):
2023-12-28 ｜ 14:15:47 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-27 (_soyo1):
2023-12-28 ｜ 14:15:47 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-29 (_soyo1):
2023-12-28 ｜ 14:15:50 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-31 (_soyo1):
2023-12-28 ｜ 14:15:52 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-33 (_soyo1):
2023-12-28 ｜ 14:15:53 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-35 (_soyo1):
2023-12-28 ｜ 14:15:53 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 48, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
2023-12-28 ｜ 14:15:54 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:15:54 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:15:55
Exception in thread Thread-7 (_soyo1):
2023-12-28 ｜ 14:15:58 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-9 (_soyo1):
2023-12-28 ｜ 14:15:59 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-11 (_soyo1):
2023-12-28 ｜ 14:16:00 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-13 (_soyo1):
2023-12-28 ｜ 14:16:04 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-15 (_soyo1):
2023-12-28 ｜ 14:16:06 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-17 (_soyo1):
2023-12-28 ｜ 14:16:13 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-19 (_soyo1):
2023-12-28 ｜ 14:16:14 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-21 (_soyo1):
2023-12-28 ｜ 14:16:18 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-23 (_soyo1):
2023-12-28 ｜ 14:16:22 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-25 (_soyo1):
2023-12-28 ｜ 14:16:24 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-27 (_soyo1):
2023-12-28 ｜ 14:16:27 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-29 (_soyo1):
2023-12-28 ｜ 14:16:28 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 92, in _soyo1
    action = Action(event)
             ^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 22, in __init__
    pure_msg = plaintext_if_prefix(pure_msg).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/message_content_tools/__init__.py", line 49, in plaintext_if_prefix
    for prefix in config['message_content_tools']['prefix']:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
2023-12-28 ｜ 14:16:32 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:16:32 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:16:33
2023-12-28 ｜ 14:17:07 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:17:07 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:17:07
2023-12-28 ｜ 14:18:59 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:18:59 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:18:59
2023-12-28 ｜ 14:26:42 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:26:42 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:27:51
2023-12-28 ｜ 14:28:08 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:28:08 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:28:38
Exception in thread Thread-1 (load_plugins):
2023-12-28 ｜ 14:28:39 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/loader.py", line 37, in load_plugins
    module = importlib.import_module(f'{folder}.{plugin_folder}')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins_kumo/poke/__init__.py", line 2, in <module>
    from bridge.tomorin import on_event, on_activator, admin_list, h, SessionExtension
ModuleNotFoundError: No module named 'bridge'
2023-12-28 ｜ 14:28:47 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:28:47 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:33:00
2023-12-28 ｜ 14:33:10 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:33:10 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:33:28
2023-12-28 ｜ 14:33:43 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:33:43 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:33:54
Exception in thread Thread-29 (_soyo1):
2023-12-28 ｜ 14:34:45 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 94, in _soyo1
    action.command(['soyo0'], ign)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 54, in command
    self._call(function)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 83, in _call
    function(self)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 123, in ign
    action.send(f'<at id="{action.event.user.id}"/> 目前支持的保留字有: G、U、P、M、F\n分别表示 Guild User Message Platform Func\n目前的逻辑列表为:\n{rpl}')
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 71, in send
    return self.event.message_create(channel_id=self.event.channel.id, content=message_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/event.py", line 129, in message_create
    return send_request(event=self, method='message.create', data={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/request.py", line 20, in send_request
    for connection in config["connections"]:
                      ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'connections'
2023-12-28 ｜ 14:34:52 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:34:52 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:35:35
Exception in thread Thread-11 (_soyo1):
2023-12-28 ｜ 14:35:42 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 15, in inner_wrapper
    return func(event)
           ^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 94, in _soyo1
    action.command(['soyo0'], ign)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 54, in command
    self._call(function)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 83, in _call
    function(self)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/event_filter/__init__.py", line 123, in ign
    action.send(f'<at id="{action.event.user.id}"/> 目前支持的保留字有: G、U、P、M、F\n分别表示 Guild User Message Platform Func\n目前的逻辑列表为:\n{rpl}')
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins/action/__init__.py", line 71, in send
    return self.event.message_create(channel_id=self.event.channel.id, content=message_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/event.py", line 129, in message_create
    return send_request(event=self, method='message.create', data={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/request.py", line 20, in send_request
    for connection in config["websockets_client"]["connections"]:
                      ~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'websockets_client'
2023-12-28 ｜ 14:35:47 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:35:47 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:35:48
2023-12-28 ｜ 14:36:10 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:36:10 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:36:45
2023-12-28 ｜ 14:36:56 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:36:56 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:37:59
2023-12-28 ｜ 14:38:09 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:38:09 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:38:56
2023-12-28 ｜ 14:39:04 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:39:04 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:39:15
2023-12-28 ｜ 14:39:30 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:39:30 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:39:44
Exception in thread Thread-10 (poke):
2023-12-28 ｜ 14:39:46 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/on.py", line 295, in inner_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/plugins_kumo/poke/__init__.py", line 70, in poke
    file_list = [f for f in os.listdir(path_) if f.endswith('.jpg') or f.endswith('.jpeg') or f.endswith('.png')]
                            ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/poke/'
2023-12-28 ｜ 14:40:09 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:40:09 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:40:10
2023-12-28 ｜ 14:41:11 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:41:11 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:44:20
2023-12-28 ｜ 14:44:44 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:44:44 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:45:59
2023-12-28 ｜ 14:46:18 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:46:18 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 14:46:19
2023-12-28 ｜ 14:46:30 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 14:46:30 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 17:09:36
2023-12-28 ｜ 17:09:54 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 17:09:54 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 17:09:54
2023-12-28 ｜ 17:10:05 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 17:10:05 ========================[END]=======================

KeyboardInterrupt
2023-12-28 ｜ 18:38:18
2023-12-28 ｜ 18:38:25 ========================[ERROR]=======================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kumo/Tomorin_v2/git/TomorinBot/core/app.py", line 19, in <module>
    2023-12-28 ｜ 18:38:25 ========================[END]=======================

KeyboardInterrupt
